package mynumberguessgame;

import validation.*;
import javax.swing.JOptionPane;


/**
 *
 * @author ryancorbin
 */
public class MyNumberGuessGameGUI extends javax.swing.JFrame {
    private MyNumberGuessProgram guesser;
    private String min;
    private String max;
    private static final String RANGE_ERR_MSG = "Range values must be numeric";

    /**
     * Creates new form MyNumberGuessGameGUI
     */
    public MyNumberGuessGameGUI() {
        initComponents();
        min = JOptionPane.showInputDialog("Enter the low end of the range: ");
        max = JOptionPane.showInputDialog("Enter the high end of the range: "); 
        titleWithRange.setText("What number am I thinking of between " + min + " and " + max);
        
        try{
            ((JTextFieldValidateable)guessSpace).setValidator(new NumericRangeValidator(min,max));
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, RANGE_ERR_MSG);
        }
        
        try{
            guesser = new MyNumberGuessProgram(min, max); 
        }catch(NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, RANGE_ERR_MSG);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleWithRange = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        guessSpace = new validation.JTextFieldValidateable(20);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleWithRange.setText("What number am I thinking of between 1 and 10?");

        jButton1.setText("Guess");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        outputLabel.setText("Guess a Number");

        jButton2.setText("Quit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        guessSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessSpaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton2)
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(guessSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(outputLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(titleWithRange)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleWithRange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guessSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String number = guessSpace.getText();
        String results = "";
        
        
        
        try{
        if(((JTextFieldValidateable)guessSpace).isFieldValid()){
            try{
                switch(guesser.checkGuess3(number)){
                    case CORRECT: results = "You guessed the number!";
                        guesser.setNumber();
                        break;
                    case LOW: results = "Too Low.  Guess Again.";
                        break;
                    case HIGH: results = "Too High.  Guess Again.";
                        break;
                }
            }catch(NumberFormatException nfe) {
                JOptionPane.showMessageDialog(rootPane, "Numbers Only Please");
            }
            outputLabel.setText(results);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Please provide a number with in the range.");
        }
        }catch (NumberFormatException nf){
             JOptionPane.showMessageDialog(rootPane, "Please Enter A Number");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void guessSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessSpaceActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_guessSpaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyNumberGuessGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyNumberGuessGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyNumberGuessGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyNumberGuessGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyNumberGuessGameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField guessSpace;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JLabel titleWithRange;
    // End of variables declaration//GEN-END:variables
}
